apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w5vovb505-go 
  janus-idp.io/tekton: w5vovb505-go
  backstage.io/kubernetes-id: w5vovb505-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w5vovb505-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml